# Docker Composeバージョン指定
# version: '3.8'

# サービス定義開始
services:
  # PostgreSQLサービス
  db:
    # PostgreSQL公式イメージ
    image: postgres:15
    # 環境変数ファイル読み込み
    env_file:
      - .env
    # データ永続化設定
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ポートマッピング
    ports:
      - "5432:5432"

  # Railsアプリサービス
  web:
    # Dockerfileからビルド
    build: .
    # 明示的に記載
    working_dir: /makemate
    # 起動コマンド
    command: sleep infinity
    # ボリュームマウント
    volumes:
      - .:/makemate
      - bundle_cache:/usr/local/bundle
    # ポートマッピング
    ports:
      - "3000:3000"
    # 依存関係（dbサービス後に起動）
    depends_on:
      - db
    # 環境変数ファイル読み込み
    env_file:
      - .env
    # 標準入力有効化
    stdin_open: true
    # TTY有効化
    tty: true

# ボリューム定義
volumes:
  # PostgreSQLデータ保存領域
  postgres_data:
  # gemキャッシュ領域
  bundle_cache:
