# 共通設定の定義（YAMLアンカー）
default: &default
  # PostgreSQLアダプター指定
  adapter: postgresql
  # 文字エンコーディング設定
  encoding: unicode
  # 接続プール数（環境変数から取得、デフォルト5）
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ユーザー名（環境変数から取得）
  username: <%= ENV['DB_USERNAME'] %>
  # パスワード（環境変数から取得）
  password: <%= ENV['DB_PASSWORD'] %>
  # ホスト名（環境変数から取得）
  host: <%= ENV['DB_HOST'] %>
  # ポート番号（環境変数から取得）
  port: <%= ENV['DB_PORT'] %>

# 開発環境設定
development:
  # 共通設定を継承
  <<: *default
  # 開発用データベース名
  database: makemate_development

# テスト環境設定
test:
  # 共通設定を継承
  <<: *default
  # テスト用データベース名
  database: makemate_test

# 本番環境設定
production:
  # 共通設定を継承
  <<: *default
  # 本番用データベース名
  database: makemate_production
  # 本番用ユーザー名（環境変数から取得）
  username: <%= ENV['DB_USERNAME'] %>
  # 本番用パスワード（環境変数から取得）
  password: <%= ENV['DB_PASSWORD'] %>
